import Authprovider from "../context/Authprovider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import Logout from "./logout";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Authprovider>
          <nav>
            {!!session && <Logout />}
            {!session && <Link href="/login">Login</Link>}
          </nav>
          {children}
        </Authprovider>
      </body>
    </html>
  );
}
